version: '3.7'
volumes:
  mongodb:
    driver: local
  mongodb_config:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
  elastic_data: {}

services:
  eureka-server:
    build: ./eurekaServer
    image: heri96/spring-cloud-gateway-eureka-server
    ports:
      - "8761:8761"

  mongodb:
    image: mongo:latest
    container_name: courses-mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  #Elasticsearch:
   # image: elasticsearch:7.16.2
    #container_name: elasticsearch
    #restart: always
    #volumes:
     # - elastic_data:/usr/share/elasticsearch/data/
    #environment:
     # ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      #discovery.type: single-node
    #ports:
     # - '9200:9200'
      #- '9300:9300'
    #networks:
     # - elk

  #Logstash:
   # image: logstash:7.16.2
    #container_name: logstash
    #restart: always
    #volumes:
     # - ./logstash/:/logstash_dir
    #command: logstash -f /logstash_dir/logstash.conf
    #depends_on:
     # - Elasticsearch
    #ports:
     # - '9600:9600'
    #environment:
     # LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    #networks:
     # - elk

  #Kibana:
   # image: kibana:7.16.2
    #container_name: kibana
    #restart: always
    #ports:
#      - '5601:5601'
 #   environment:
  #    - ELASTICSEARCH_URL=http://elasticsearch:9200
   # depends_on:
    #  - Elasticsearch
#    networks:
#      - elk

  config-server:
    build: ./configServer
    image: configserver-image
    ports:
      - "8888:8888"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
